### ISSUE TITLE
Update PerfUtil to latest version to avoid binding exceptions

### ISSUE THREAD

**Issue by haf** [mausch/Fuchu#37]

**Comment by mausch** [comment]
I'm getting compile-time errors while upgrading from the currently targeted version 0.1.5 to 0.1.8:

* `No assignment given for field 'Repeat' of type 'PerfUtil.PerfTest<_>'	Fuchu.PerfUtil\PerfUtil.fs	19`
* `No overloads match for method 'PastImplementationComparer```1'. Fuchu.PerfUtil\PerfUtil.fs 114`

Please send me a pull request or point me to whatever I have to change about this.

**Comment by haf** [comment]
see https://github.com/mausch/Fuchu/pull/38/files?w=1#diff-d37fa8a24fbfee6d8485ba58613659ccR19

**Comment by mausch** [comment]
Cheers, I'll take a look.

**Comment by mausch** [comment]
Upgraded to PerfUtil 0.1.8 in https://github.com/mausch/Fuchu/commit/86c6614f09cc447b141934bdc7d7740235e0a91e
