### ISSUE TITLE
Assert expected, actual -> Assert actual, expected

### ISSUE THREAD

**Issue by haf** [mausch/Fuchu#40]
Switching order for these would make it easier to read:

`I Assert.Equal("because some context, that", ``computed value`` (), "is this string"`).

**Comment by mausch** [comment]
Assertion syntax is highly subjective... it's why I didn't even want to include assertions in Fuchu at first. Most of the time I end up writing my own assertions functions anyway, tailored to the domain I'm testing ( https://github.com/mausch/Fuchu#assertions ). Or even just simply throw an `AssertException` via `failtest` / `failtestf`.

For your particular request, you could shadow the original definition of `Assert.Equal` in your project:

```
module Assert =
    let Equal (msg, actual, expected) = Assert.Equal(msg, expected, actual)
```

**Comment by haf** [comment]
Yes, I know, but when it comes to 'quick to work with' having assertions in the lib is a good idea.

**Comment by haf** [comment]
https://github.com/haf/expecto-patronum
