### ISSUE TITLE
Add Fuchu pronunciation to README

### ISSUE THREAD

**Issue by voronoipotato** [mausch/Fuchu#52]
Currently there is no pronunciation guide for "Fuchu". Is it like "Foo choo", "Fuh choo", "Fuhkoo", or "foo koo" or something entirely different .

**Comment by mausch** [comment]
Heh, good point. It's "foo choo" with the accent on the last syllable.

**Comment by mausch** [comment]
Updated README in https://github.com/mausch/Fuchu/commit/a2bbe6c6a01b1eced4e0fdf02d180fc78aada4a4 .
Thanks!

**Comment by voronoipotato** [comment]
No problem, look forward to trying it :).
